[workspace]
members = ["gameboy_emulator", "gameboy_emulator_lib"]

[workspace.dependencies]
serde = { version = "1", featues = ["derive"] }
clap = { version = "4.0.32", features = ["derive"] }

[profile.release]
opt-level = 2 # fast and small wasm
